# 선언적으로 비동기 처리하기

<div style="margin-top: 16px">
  <Badge type="info" text="Suspense" />
  <Badge type="info" text="ErrorBoundary" />
</div>

## 🔔 상황

로딩, 에러, 성공과 같은 비동기 상태를 하나의 컴포넌트에서 관리하면 큰 책임을 담당하기 때문에 다양한 맥락이 혼재되어 구현 부분에 많은 분기가 추가됩니다. 이는 컴포넌트의 동작을 파악하기 어렵게 만들어 역할을 이해하는 데 어려움을 줄 수 있고, 수정 시 영향 범위가 커서 예상치 못한 부작용이 발생할 수도 있습니다.

## 🎳 해결법

각 상태별로 책임을 분리하면, 각 컴포넌트는 더 작은 책임 담당하기 때문에 가독성은 높아지고 결합도는 낮아집니다.

- 로딩 상태: `Suspense` 컴포넌트
- 에러 상태: `ErrorBoundary` 컴포넌트
- 성공 상태: `데이터를_처리하는_컴포넌트`

:::info
가독성이 높아지고 결합도가 낮아지는 이유를 자세히 알고 싶다면, [로직 종류에 따라 합쳐진 함수 쪼개기](../criteria-for-good-code/로직-종류에-따라-합쳐진-함수-쪼개기), [책임을 하나씩 관리하기](../criteria-for-good-code/책임을-하나씩-관리하기)를 확인해 봅시다.
:::

## Suspense

`Suspense` 를 사용하면 로딩 상태를 선언적으로 처리할 수 있습니다. 자식 컴포넌트가 완료(fulfilled)되거나 실패(rejected)하기 전까지 fallback UI를 렌더링합니다.

TanStack Query, SWR 라이브러리 등을 함께 사용하면 비동기 상태를 간단하게 처리할 수 있습니다.

:::info
비동기 상태 관리 라이브러리를 사용하는 이유를 자세히 알고 싶다면, [TkDodo](https://x.com/TkDodo?ref_src=twsrc%5Etfw)가 작성한 [Why you want react query](https://tkdodo.eu/blog/why-you-want-react-query)를 확인해 봅시다.
:::

::: code-group

```tsx [ProductPage.tsx]
function ProductPage() {
  return (
    <Suspense fallback={<Loading />}>
      <Product />
    </Suspense>
  );
}
```

```tsx [Product.tsx]
function Product() {
  const { data } = useSuspenseQuery({
    queryKey: ["product"],
    queryFn: fetchProduct,
  });
  // ...
}
```

:::

:::tip
`Suspense` 는 비동기 상태를 알아야 `fallback` 컴포넌트와 자식 컴포넌트 중 어느 것을 렌더링할지 결정할 수 있습니다. 핵심 아이디어는 비동기 요청의 `promise` 를 `throw` 하고, `Suspense`가 `getDerivedStateFromError` 메서드를 사용하여 이를 캐치하는 것입니다. 이를 통해 `Suspense` 는 `promise` 의 상태(pending, fulfilled, rejected)를 알 수 있습니다.
:::

## ErrorBoundary

기본적으로 React 애플리케이션에서 렌더링 중 오류가 발생하면 React는 해당 UI를 화면에서 제거합니다. 이를 방지하려면 UI 일부를 `ErrorBoundary` 로 감싸야 합니다. `ErrorBoundary` 는 오류가 발생한 부분을 감지하고, 대신 fallback UI(예: 오류 메시지)를 표시할 수 있는 컴포넌트입니다.

또한, ErrorBoundary는 에러 상태를 선언적으로 처리할 수 있습니다. 내부적으로 `getDerivedStateFromError` 메서드를 사용하여 `throw` 된 오류를 감지하고 적절한 UI를 렌더링합니다.

:::info
`ErrorBoundary` 를 언제 사용해야 하는지 자세히 알고 싶다면, [에러 경계 세분화하기](./에러-경계-세분화하기)를 확인해 봅시다.
:::

아래 코드는 에러를 캐치하면, fallback UI를 렌더링하는 기능만 포함하고 있습니다.

```tsx
interface ErrorBoundaryState<ErrorType extends Error = Error> {
  error: ErrorType | null;
}

const initialState: ErrorBoundaryState = {
  error: null,
};

class ErrorBoundary extends Component {
  state = initialState;

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  render() {
    const { children } = this.props;
    const { error } = this.state;

    if (error != null) {
      return <h1>에러 메시지</h1>;
    }

    return children;
  }
}
```

유용한 기능을 추가하여 ErrorBoundary를 확장해 봅시다.

### onError, ignoreError props

에러가 발생하면 모니터링을 위해 로깅하는 것이 좋습니다. 이를 위해 `onError` prop으로 에러와 에러 정보를 인자로 받는 콜백 함수를 전달할 수 있습니다. 에러가 발생하면 해당 콜백을 호출하여 로깅을 수행합니다.

그러나 모든 에러를 현재 `ErrorBoundary` 에서 처리할 수 있는 것은 아닙니다. 예를 들어, 전역적으로 처리해야 하는 에러나 예상치 못한 에러가 있을 수 있습니다. 이를 상위 `ErrorBoundary` 로 위임하려면, 에러를 인자로 받는 콜백 함수를 `ignoreError` prop으로 전달합니다.

:::code-group

```tsx [Component.tsx]
<ErrorBoundary
  onError={(error, info) => {
    logging(error.message, info.componentStack);
  }}
  ignoreError={(error) => isGlobalError(error)}
>
  <에러를_발생시킬_수_있는_컴포넌트 />
</ErrorBoundary>
```

```tsx [ErrorBoundary.tsx]
class ErrorBoundary extends Component {
  // ...
  componentDidCatch(error: Error, info: ErrorInfo) {
    const { onError, ignoreError } = this.props;

    if (ignoreError?.(error)) {
      throw error;
    }

    onError?.(error, info);
  }
  // ...
}
```

:::

### resetKeys, onReset props

`ErrorBoundary` 의 에러는 상태로 관리되기 때문에, 부모 컴포넌트가 다시 마운트되지 않는 한 fallback UI가 계속 렌더링됩니다. 이를 해결하려면 에러를 초기화하여, 에러가 발생했던 자식 컴포넌트를 다시 렌더링할 수 있습니다.

에러를 초기화하는 방법:

- `onRest`: fallback UI에서 "다시 불러오기" 또는 "재시도" 버튼을 클릭하면 에러를 리셋
- `resetKeys`: 자식 컴포넌트의 특정 의존 값이 변경되면 에러를 자동으로 리셋

:::tip
리셋할 때 함께 초기화해야 할 값이 있을 수도 있습니다. 예를 들어, TanStack Query로 호출한 API에서 발생한 에러는 캐싱되므로, 리셋 시점에 `QueryErrorResetBoundary` 또는 u`seQueryErrorResetBoundary` 를 사용해 캐싱된 에러도 함께 초기화해야 합니다.
:::

:::code-group

```tsx [Component.tsx]
<QueryErrorResetBoundary>
  {({ reset }) => (
    <ErrorBoundary resetKeys={[key1, key2]} onReset={reset}>
      <에러를_발생시킬_수_있는_컴포넌트 />
    </ErrorBoundary>
  )}
</QueryErrorResetBoundary>
```

```tsx [ErrorBoundary.tsx]
class ErrorBoundary extends Component {
  // ...
  resetState() {
    this.setState(initialState);
  }

  resetErrorBoundary = () => {
    this.props.onReset?.();
    this.resetState();
  };

  componentDidUpdate(prevProps: ErrorBoundaryProps) {
    const { error } = this.state;

    if (error == null) {
      return;
    }

    const { resetKeys } = this.props;

    if (isDifferentArray(prevProps.resetKeys, resetKeys)) {
      this.resetErrorBoundary();
    }
  }

  render() {
    const { children } = this.props;
    const { error } = this.state;

    if (error != null) {
      return (
        <>
          <h1>에러 메시지</h1>
          <button onClick={this.resetErrorBoundary}>재시도</button>
        </>
      );
    }

    return children;
  }
}
```

```typescript [isDifferentArray.ts]
function isDifferentArray(a: unknown[] = [], b: unknown[] = []) {
  return (
    a.length !== b.length || a.some((item, index) => !Object.is(item, b[index]))
  );
}
```

:::

### renderFallback prop

에러가 발생하면 지정된 fallback UI를 렌더링할 수 있도록, 에러 객체와 에러 상태를 리셋하는 메서드를 인자로 받는 fallback 함수를 `renderFallback` prop으로 전달합니다.

:::code-group

```tsx [Component.tsx]
<ErrorBoundary
  renderFallback={({ error, reset }) => (
    <>
      <h1>{error.message}</h1>
      <button onClick={reset}>retry</button>
    </>
  )}
>
  <에러를_발생시킬_수_있는_컴포넌트 />
</ErrorBoundary>
```

```tsx [ErrorBoundary.tsx]
class ErrorBoundary extends Component {
  // ...
  render() {
    const { children, renderFallback } = this.props;
    const { error } = this.state;

    if (error != null) {
      return renderFallback({
        error,
        reset: this.resetErrorBoundary,
      });
    }

    return children;
  }
}
```

:::
